Repository juanmc2005/diart, pull requests merged in 2021-12, with the labels that each got.

#3 Make installable package
  pyproject.toml
  setup.cfg
  setup.py
  src/diart/__init__.py
  src/diart/demo.py
  src/diart/functional.py
  src/diart/mapping.py
  src/diart/operators.py
  src/diart/pipelines.py
  src/diart/sinks.py
  src/diart/sources.py
  src/diart/utils.py
Labels: enhancement

#16 Replace `operators.aggregate()` with `functional.DelayedAggregation`
  src/diart/functional.py
  src/diart/operators.py
  src/diart/pipelines.py
Labels: bug, documentation, enhancement

#18 Add Hamming-weighted average to `DelayedAggregation`
  requirements.txt
  setup.cfg
  src/diart/demo.py
  src/diart/functional.py
  src/diart/mapping.py
  src/diart/operators.py
  src/diart/pipelines.py
  src/diart/sinks.py
  src/diart/sources.py
Labels: bug, enhancement

#19 Asynchronous microphone reading
  src/diart/demo.py
  src/diart/functional.py
  src/diart/mapping.py
  src/diart/operators.py
  src/diart/pipelines.py
  src/diart/sinks.py
  src/diart/sources.py
  src/diart/utils.py
Labels: bug, documentation, enhancement
