Repository juanmc2005/diart, pull requests merged in 2022-06, with the labels that each got.

#59 Replace `resolve_features` with `TemporalFeatureFormatter`
  src/diart/blocks.py
  src/diart/features.py
Labels: refactoring

#61 Make `pyannote.audio` optional (still mandatory to run default pipeline)
  README.md
  requirements.txt
  setup.cfg
  src/diart/argdoc.py
  src/diart/audio.py
  src/diart/benchmark.py
  src/diart/blocks.py
  src/diart/features.py
  src/diart/inference.py
  src/diart/models.py
  src/diart/pipelines.py
  src/diart/sinks.py
  src/diart/sources.py
  src/diart/stream.py
Labels: documentation, feature, API

#31 Adds documentation for some of the classes and methods
  src/diart/blocks/clustering.py
  src/diart/mapping.py
  src/diart/pipelines.py
Labels: documentation
