Repository juanmc2005/diart, pull requests merged in 2023-11, with the labels that each got.

#188 Add compatibility with pyannote 3.0 embedding wrappers
  requirements.txt
  setup.cfg
  src/diart/argdoc.py
  src/diart/blocks/clustering.py
  src/diart/blocks/diarization.py
  src/diart/blocks/embedding.py
  src/diart/console/benchmark.py
  src/diart/console/serve.py
  src/diart/console/stream.py
  src/diart/console/tune.py
  src/diart/models.py
Labels: feature, API

#198 Add support for powerset segmentation models
  src/diart/blocks/embedding.py
  src/diart/models.py
Labels: feature

#209 Add documentation page
  .readthedocs.yaml
  README.md
  docs/Makefile
  docs/_static/logo.png
  docs/conf.py
  docs/index.rst
  docs/make.bat
  docs/requirements.txt
  src/diart/blocks/base.py
  src/diart/blocks/diarization.py
  src/diart/blocks/embedding.py
  src/diart/models.py
Labels: documentation

#216 Add reproducibility warning in README
  README.md
  setup.cfg
Labels: documentation, ops
