Repository juanmc2005/diart, pull requests merged in 2023-10, with the labels that each got.

#172 [joss] Add Conda environment
  README.md
  environment.yml
Labels: ops

#179 [joss] Use ABC and abstractmethod rather than NotImplementedError (rebased)
  src/diart/blocks/aggregation.py
  src/diart/blocks/base.py
  src/diart/blocks/diarization.py
  src/diart/features.py
  src/diart/mapping.py
  src/diart/models.py
  src/diart/progress.py
  src/diart/sources.py
Labels: refactoring

#153 Fix sample rate issues
  README.md
  src/diart/blocks/base.py
  src/diart/blocks/utils.py
  src/diart/console/client.py
  src/diart/console/stream.py
  src/diart/inference.py
  src/diart/sources.py
Labels: bug

#181 Fix torchaudio version incompatibility
  requirements.txt
  setup.cfg
Labels: ops, urgent

#182 Add special audio source for Apple devices
  src/diart/argdoc.py
  src/diart/blocks/aggregation.py
  src/diart/blocks/base.py
  src/diart/blocks/clustering.py
  src/diart/blocks/diarization.py
  src/diart/blocks/embedding.py
  src/diart/blocks/segmentation.py
  src/diart/blocks/utils.py
  src/diart/blocks/vad.py
  src/diart/console/benchmark.py
  src/diart/console/client.py
  src/diart/console/serve.py
  src/diart/console/stream.py
  src/diart/console/tune.py
  src/diart/features.py
  src/diart/inference.py
  src/diart/models.py
  src/diart/operators.py
  src/diart/optim.py
  src/diart/progress.py
  src/diart/sinks.py
  src/diart/sources.py
  src/diart/utils.py
Labels: bug

#183 Catch keyboard interrupt in `diart.stream`
  src/diart/console/stream.py
Labels: API

#189 Remove `PipelineConfig.from_dict()`
  README.md
  src/diart/blocks/base.py
  src/diart/blocks/diarization.py
  src/diart/blocks/vad.py
  src/diart/console/benchmark.py
  src/diart/console/client.py
  src/diart/console/serve.py
  src/diart/console/stream.py
  src/diart/console/tune.py
  src/diart/utils.py
Labels: refactoring

#191 Fix link to reproducibility section
  README.md
Labels: documentation
